### ISSUE TITLE
Documentation fix for createOpenvzContainer

### ISSUE THREAD

**Issue by m-o-n-k** [Daemonthread/pyproxmox#14]
There is a critical documentation bug within your first example for createOpenvzContainer:

```post_data = {'ostemplate':'localvztmpl/debian-6.0-standard_6.0-4_amd64.tar.gz',```
The ":" is missing within this line. It has to be:
```post_data = {'ostemplate':'local:vztmpl/debian-6.0-standard_6.0-4_amd64.tar.gz',```

This cost me 3 hours of my life to find out. :(

**Comment by Daemonthread** [comment]
Thanks for reporting this and sorry for the wasted time.

Fix pushed https://github.com/Daemonthread/pyproxmox/commit/e8b6f999a28e258878bdf12200906bfdb7a22622
